import type { AccountRole } from '@/lib/auth/roles';

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, 'owner'>;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

/**
 * Where a contact first entered the account (`contacts.source`,
 * migration 056). Mirrors CONTACT_SOURCES in
 * apps/api/src/common/contacts/contact-source.ts and the
 * `contacts_source_chk` constraint — keep all three in step.
 */
export type ContactSource =
  | 'manual'
  | 'import'
  | 'whatsapp'
  | 'instagram'
  | 'web'
  | 'form'
  | 'facebook_lead'
  | 'api'
  | 'broadcast'
  | 'unknown';

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  /**
   * NULL for Instagram-only contacts (migration 050 dropped the NOT
   * NULL). Anything rendering this must handle the absence — prefer
   * `ig_username` when it's missing.
   */
  phone: string | null;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. NULL when `phone` is. */
  phone_normalized?: string | null;
  /** Instagram-scoped user ID. Present iff the contact came from Instagram. */
  ig_scoped_id?: string | null;
  /** Cached @handle. Display only — Instagram usernames are mutable. */
  ig_username?: string | null;
  /**
   * Opaque browser id for a web-widget visitor. Account-scoped and
   * meaningless outside this tenant. NULL for every non-web contact.
   * Read-only here, but load-bearing: `contacts_identity_chk` needs a
   * phone OR an `ig_scoped_id` OR this, so it decides whether a phone
   * number may be cleared.
   */
  web_visitor_id?: string | null;
  name?: string;
  email?: string;
  company?: string;
  avatar_url?: string;
  /**
   * How this contact first entered the account (migration 056). Written
   * once at creation, never updated. Optional here because select
   * projections that predate the column omit it — render it through
   * `contactSourceMeta` in lib/contacts/source.ts, which treats an
   * absent value the same as `'unknown'`.
   */
  source?: ContactSource | null;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

/**
 * A named, reusable audience (migration 076).
 *
 * `static` carries an explicit membership list and is the only kind
 * anything can add a contact to. `dynamic` is a saved filter whose
 * membership is computed from `filter` on read, so it can never go
 * stale — and can never be edited by hand.
 */
export type SegmentKind = 'static' | 'dynamic';

export interface ContactSegment {
  id: string;
  account_id: string;
  user_id: string | null;
  name: string;
  description: string | null;
  color: string;
  kind: SegmentKind;
  filter: SegmentFilter;
  created_at: string;
  updated_at: string;
}

/** A segment plus the number of people currently in it. */
export interface ContactSegmentWithCount extends ContactSegment {
  member_count: number;
}

export type SegmentRuleField =
  | 'tag'
  | 'source'
  | 'has_phone'
  | 'name'
  | 'email'
  | 'company'
  | 'created_at'
  /** Encoded as `custom:<custom_field_id>`. */
  | string;

export type SegmentRuleOperator =
  | 'has'
  | 'not_has'
  | 'is'
  | 'is_not'
  | 'contains'
  | 'is_set'
  | 'is_not_set'
  | 'before'
  | 'after';

export interface SegmentRule {
  field: SegmentRuleField;
  op: SegmentRuleOperator;
  value?: string;
}

export interface SegmentFilter {
  /** 'all' = every rule must match (AND); 'any' = at least one (OR). */
  match?: 'all' | 'any';
  rules?: SegmentRule[];
}

/** Which surface filed a contact into a segment. */
export type SegmentMemberSource =
  'manual' | 'import' | 'automation' | 'flow' | 'api' | 'broadcast';

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  user_id: string;
  note_text: string;
  created_at: string;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

/**
 * Platforms a conversation can live on (`conversations.channel`,
 * migrations 050 and 053). Mirrors CHANNELS in apps/api's
 * common/messaging — keep the two in step.
 */
export type ConversationChannel = 'whatsapp' | 'instagram' | 'web';

export interface Conversation {
  id: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  /**
   * Optional in the type, never null in the DB — the column has a
   * `whatsapp` default, but Supabase Realtime payloads for rows written
   * before a client refresh can arrive without it. Read it through
   * `conversationChannel()` rather than directly.
   */
  channel?: ConversationChannel;
  assigned_agent_id?: string;
  last_message_text?: string;
  last_message_at?: string;
  /**
   * Most recent customer message. On Instagram this is what the
   * 24-hour reply window counts from; on WhatsApp it is informational.
   */
  last_inbound_at?: string | null;
  unread_count: number;
  /**
   * AI auto-reply is paused on THIS thread.
   *
   * Set automatically the moment a human replies — from the dashboard or
   * from the Instagram app, see HumanTakeoverService on the API side —
   * and cleared only by someone switching the bot back on in the thread
   * header. Sticky on purpose: a bot that goes quiet and then rejoins a
   * conversation half an hour later is the same surprise, just delayed.
   */
  ai_autoreply_disabled?: boolean;
  /**
   * Which AI agent owns this thread (migration 084).
   *
   * Set on the first AI reply and then STICKY — the resolver consults it
   * before channel and priority, so a thread never changes personality
   * mid-conversation. Writing it by hand from the inbox's Owner control is
   * therefore how you hand a conversation to a specific agent.
   */
  ai_agent_id?: string | null;
  created_at: string;
  updated_at: string;
  contact?: Contact;
}

// ============================================================
// Notifications (migration 027)
// ============================================================

export type NotificationType = 'conversation_assigned';

export interface Notification {
  id: string;
  account_id: string;
  /** Recipient — the agent this notification is for. */
  user_id: string;
  type: NotificationType;
  conversation_id?: string;
  contact_id?: string;
  /** Who triggered it. Null when an automation/system assigned it. */
  actor_user_id?: string;
  title: string;
  body?: string;
  read_at?: string;
  created_at: string;
}

export type SenderType = 'customer' | 'agent' | 'bot';
/**
 * How to render a message. Mirrors `messages_content_type_check`
 * (migration 062) — every value here needs a case in `MessageContent`
 * (components/inbox/message-bubble.tsx), and vice versa.
 *
 * Note there is no `'button'`: a tap on a *template's* quick-reply
 * button means the same thing as a tap on an interactive button, so
 * both are stored as `'interactive'` and told apart by
 * `metadata.source`.
 */
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive'
  | 'sticker'
  /** Contact card(s) shared by the customer. */
  | 'contacts'
  /** Cart submitted from the catalog. */
  | 'order'
  /** Platform notice — the customer changed their number, etc. */
  | 'system'
  /**
   * A forwarded Instagram post or reel. `media_url` is always null —
   * the content stays on Instagram and we keep only a permalink in
   * `metadata.ig_permalink`. See migration 065.
   */
  | 'share'
  /** WhatsApp itself could not forward what was sent. */
  | 'unsupported';
export type MessageStatus =
  'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Everything the renderer needs beyond `content_text` and
   * `media_url`. Written by the API — see
   * apps/api/src/common/messages/message-content.types.ts, which this
   * mirrors. Shared with the Instagram channel, so treat unknown keys
   * as someone else's and never overwrite the whole object.
   */
  metadata?: MessageMetadata | null;
}

/** A template button exactly as the customer saw it. */
export interface MessageTemplateButton {
  type: 'QUICK_REPLY' | 'URL' | 'PHONE_NUMBER' | 'COPY_CODE';
  text: string;
  url?: string;
  phone_number?: string;
}

/**
 * What an outbound template looked like on the customer's phone,
 * captured at send time.
 *
 * Meta renders templates from its own approved copy and returns only a
 * message id, so this is the only record of the header image, footer
 * and buttons that were actually delivered. Absent on rows sent before
 * migration 062 — the bubble falls back to body text alone.
 */
export interface MessageTemplateSnapshot {
  name: string;
  language?: string | null;
  header?: {
    type: 'TEXT' | 'IMAGE' | 'VIDEO' | 'DOCUMENT' | 'LOCATION';
    text?: string | null;
    media_url?: string | null;
    filename?: string | null;
  } | null;
  footer?: string | null;
  buttons?: MessageTemplateButton[];
}

export interface MessageContactCard {
  name: string;
  phones: Array<{ phone: string; type?: string | null }>;
  emails?: Array<{ email: string; type?: string | null }>;
  organization?: string | null;
}

export interface MessageOrderItem {
  retailer_id: string;
  name?: string | null;
  quantity: number;
  unit_price: number;
  currency?: string | null;
}

export interface MessageMetadata {
  /** Origin of an 'interactive' row: which kind of tap produced it. */
  source?: 'template_button' | 'interactive_reply' | 'flow_reply';
  template?: MessageTemplateSnapshot;
  contacts?: MessageContactCard[];
  order?: {
    catalog_id?: string | null;
    items: MessageOrderItem[];
    total?: number;
    currency?: string | null;
    note?: string | null;
  };
  location?: {
    latitude: number;
    longitude: number;
    name?: string | null;
    address?: string | null;
  };
  error?: {
    code?: number | null;
    title?: string | null;
    detail?: string | null;
  };
  flow_response?: Record<string, unknown>;
  animated?: boolean;
  /** Instagram keys — owned by that channel, listed so they aren't stripped. */
  title?: string;
  ig_attachment_type?: string;
  reel_video_id?: string;
  ig_source_url_expired?: boolean;
  /**
   * instagram.com link for a forwarded post or reel. We keep the
   * reference and never a copy — see migration 065.
   */
  ig_permalink?: string;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  phone_number_id: string;
  waba_id?: string;
  access_token: string;
  verify_token?: string;
  status: 'connected' | 'disconnected';
  connected_at?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. */
  last_registration_error?: string;
  /** How these credentials were obtained. Defaults to 'manual' for pre-existing rows. */
  connection_method?: 'manual' | 'embedded_signup';
  /** Meta Business ID that owns the WABA (Embedded Signup only). */
  business_id?: string;
  /** True when the number stays on the WhatsApp Business App instead of migrating to the Cloud API. */
  coexistence?: boolean;
  /** Set for embedded_signup rows — the long-lived user token's expiry (~60 days out). Null for manual rows. */
  token_expires_at?: string;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

/**
 * Meta's `parameter_format`. POSITIONAL is the classic `{{1}}` scheme;
 * NAMED swaps it for `{{customer_name}}`. A template is one or the
 * other — Meta rejects a mix — and the format is fixed once created.
 */
export type TemplateParameterFormat = 'POSITIONAL' | 'NAMED';

/**
 * One card of a CAROUSEL template. Meta requires every card in a
 * carousel to share the same shape: same header format, and the same
 * number and types of buttons. Cards have no footer.
 */
export interface TemplateCard {
  header_format: 'image' | 'video';
  /** Resumable-Upload handle — what Meta wants for card media at creation. */
  header_handle?: string;
  /** Public sample URL. Also the send-time media source for this card. */
  header_media_url?: string;
  body_text: string;
  /** Sample values for the card body's variables, in placeholder order. */
  body_samples?: string[];
  buttons: TemplateButton[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document' | 'location';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  /** Defaults to POSITIONAL when absent — every pre-existing row. */
  parameter_format?: TemplateParameterFormat;
  /** Non-empty only for CAROUSEL templates. */
  cards?: TemplateCard[];
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  created_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  created_at: string;
}

export type DealStatus = 'open' | 'won' | 'lost';

export interface Deal {
  id: string;
  user_id: string;
  pipeline_id: string;
  stage_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  conversation_id?: string;
  assigned_to?: string;
  title: string;
  value: number;
  currency?: string;
  notes?: string;
  expected_close_date?: string;
  status?: DealStatus;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  stage?: PipelineStage;
  assignee?: Profile;
}

/**
 * `queued` (migration 070) sits between draft and sending: accepted and
 * handed to the delivery queue, but no message has left yet. It exists
 * because delivery fans out into one job per recipient, so there is a
 * real interval — rate-limited, and longer for a big audience — where
 * "nothing has arrived" is the correct and expected state.
 */
export type BroadcastStatus =
  'draft' | 'queued' | 'scheduled' | 'sending' | 'sent' | 'failed';
export type RecipientStatus =
  'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  template_name: string;
  template_language: string;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based'
  // Instagram-specific triggers — these have no WhatsApp equivalent and
  // lock the automation to the Instagram channel when selected.
  | 'instagram_comment'
  | 'instagram_story_reply'
  // Web widget-only: a visitor opened a chat and sent their first message.
  | 'web_chat_started'
  // Form submitted — channel-agnostic, hosted submissions have no channel.
  | 'form_submitted'
  // Appointment lifecycle — also channel-agnostic.
  | 'appointment_booked'
  | 'appointment_cancelled'
  | 'appointment_rescheduled';

/**
 * Mirrors AutomationStepType in
 * apps/api/src/automations/automation.types.ts. There is no shared types
 * package yet; a type added on one side and not the other saves fine and
 * then fails at run time, so change both together.
 */
export type AutomationStepType =
  | 'send_message'
  | 'send_template'
  // Media and interactive sends. Routed per conversation channel, so
  // they work on WhatsApp, Instagram and web — except lists, which
  // Instagram has no equivalent for and which skip there.
  | 'send_media'
  | 'send_buttons'
  | 'send_list'
  | 'add_tag'
  | 'remove_tag'
  // Put the contact into (or take them out of) a named audience. A tag
  // describes the person; a segment is a list a broadcast can be aimed
  // at. Static segments only — a dynamic one computes its own members.
  | 'add_to_segment'
  | 'remove_from_segment'
  | 'assign_conversation'
  | 'update_contact_field'
  // Stores a value in `vars` for later steps — the glue between a step
  // that produces data and a step that needs it shaped.
  | 'set_variable'
  | 'create_deal'
  | 'update_deal'
  // Internal note on the contact's timeline; team-only.
  | 'add_note'
  // In-app notification for one member or the whole workspace.
  | 'notify_team'
  | 'wait'
  // Holds until a wall-clock time rather than for a duration.
  | 'wait_until'
  | 'condition'
  // Percentage split down the same yes/no branches a condition uses.
  | 'random_split'
  // HTTP request whose response later steps can read. `send_webhook` is
  // its fire-and-forget ancestor, kept so existing automations run.
  | 'http_request'
  // A named action on a connected app — \"Google Sheets: Append row\".
  // ONE step type for every app and every action: the app and action are
  // data in step_config, resolved through the connector catalogue served
  // by GET /api/connections/catalog. The picker still lists each action
  // separately. See docs/app-connections.md.
  // ⚠️ DEPRECATED — replaced by `google_action`. Kept so saved automations
  // still render; the executor no longer handles it.
  | 'app_action'
  // A Google action executed via the workspace's Apps Script bridge.
  // Config is `{ action, input }` — no connection_id, no app field.
  // The bridge serves Gmail, Calendar, Meet and Sheets through one
  // deployment. Catalogue served by GET /api/google-script/catalog.
  | 'google_action'
  | 'send_webhook'
  | 'close_conversation'
  | 'set_conversation_status'
  // Hands the contact over to a Flow.
  | 'start_flow'
  // Runs another automation as a sub-routine (depth-guarded).
  | 'run_automation'
  // Sends a form link (or inline card on web) to the contact.
  | 'send_form'
  // Sends a booking page link to the contact.
  | 'send_booking_link';

export type AutomationLogStatus = 'success' | 'partial' | 'failed';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  match_type: 'exact' | 'contains';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | FormSubmittedTriggerConfig
  | AppointmentTriggerConfig
  | Record<string, unknown>;

/** Config for form_submitted trigger. */
export interface FormSubmittedTriggerConfig {
  /** Omitted = any form in the account. */
  form_id?: string;
}

/** Config for appointment_* triggers. */
export interface AppointmentTriggerConfig {
  /** Omitted = any appointment type. */
  appointment_type_id?: string;
}

export interface SendMessageStepConfig {
  text: string;
}

export interface SendTemplateStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface SegmentStepConfig {
  segment_id: string;
}

export interface AssignConversationStepConfig {
  mode: 'specific' | 'round_robin';
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
}

export type ConditionSubject =
  'contact_field' | 'tag_presence' | 'message_content' | 'time_of_day';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendTemplateStepConfig
  | TagStepConfig
  | SegmentStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  /**
   * Channels this automation runs on. Empty array = all channels (the
   * default for every automation created before migration 052).
   */
  channels: string[];
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  /** Channel of the conversation that triggered this run. NULL = unknown or time-based. */
  channel: string | null;
  error_message?: string | null;
  created_at: string;
  contact?: Contact & { ig_username?: string | null };
}

// ============================================================
// CTWA Campaigns (migration 034)
// ============================================================

export type CTWACampaignStatus = 'active' | 'paused' | 'archived';

export interface CTWACampaign {
  id: string;
  account_id: string;
  name: string;
  meta_ad_id?: string;
  meta_campaign_id?: string;
  pre_filled_message?: string;
  deep_link_url?: string;
  status: CTWACampaignStatus;
  click_count: number;
  conversation_count: number;
  created_at: string;
  updated_at: string;
}

export interface CTWAClick {
  id: string;
  campaign_id: string;
  contact_id?: string;
  conversation_id?: string;
  click_timestamp: string;
  user_agent?: string;
  referrer?: string;
  ip_address?: string;
  converted: boolean;
  converted_at?: string;
}

// ============================================================
// E-commerce Integrations (migration 035)
// ============================================================

export type EcommercePlatform = 'shopify' | 'woocommerce';

export type EcommerceIntegrationStatus = 'connected' | 'disconnected' | 'error';

export interface EcommerceIntegration {
  id: string;
  account_id: string;
  platform: EcommercePlatform;
  store_url: string;
  api_key?: string;
  api_secret?: string;
  access_token?: string;
  status: EcommerceIntegrationStatus;
  last_sync_at?: string;
  sync_error?: string;
  created_at: string;
  updated_at: string;
}

export interface EcommerceProduct {
  id: string;
  integration_id: string;
  external_product_id: string;
  name: string;
  description?: string;
  price: number;
  currency: string;
  image_url?: string;
  product_url: string;
  inventory_count?: number;
  sync_at: string;
}

export interface EcommerceOrder {
  id: string;
  integration_id: string;
  external_order_id: string;
  contact_id?: string;
  total_amount: number;
  currency: string;
  status: string;
  order_url: string;
  sync_at: string;
}

// ============================================================
// Campaign Scheduler & Retargeting (migration 036)
// ============================================================

export type CampaignType = 'broadcast' | 'retargeting';

export interface CampaignSchedule {
  id: string;
  account_id: string;
  name: string;
  type: CampaignType;
  broadcast_id?: string;
  retargeting_config?: Record<string, unknown>;
  schedule_type: 'one_time' | 'recurring';
  scheduled_at: string;
  recurring_pattern?: string; // cron expression
  timezone?: string;
  status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';
  last_run_at?: string;
  next_run_at?: string;
  run_count: number;
  created_at: string;
  updated_at: string;
}
