-- ============================================================
-- 092_google_script_connections.sql
--   Replaces OAuth app connections (082) with customer-deployed
--   Apps Script bridges.
--
-- Guide: docs/google-apps-script.md. Read it before changing this.
--
-- WHY THIS EXISTS AT ALL
--
--   082 had Converse360 calling Google's APIs, which put the product
--   behind Google's OAuth verification review: an unverified-app
--   interstitial on every customer's consent screen and a hard,
--   unresettable 100-grant lifetime cap on the project. This inverts
--   the direction. The customer deploys a small Apps Script web app in
--   their OWN Google account and pastes its URL here; the script does
--   the Gmail / Calendar / Meet / Sheets work under their own
--   authority. Google is never asked to verify us, because we never
--   call Google.
--
--   The costs are real and documented in the guide: no update channel
--   for a script living in someone else's account, per-customer Apps
--   Script quotas (Gmail sending is the binding one), and failures that
--   land in their execution log rather than ours.
--
-- WHAT THIS IS
--
--   ONE ROW PER WORKSPACE. Unlike 082 there is no provider and no
--   external account: a workspace has at most one bridge, and that
--   bridge covers all four Google products at once because a single
--   Apps Script deployment answers every action. `account_id` is
--   therefore UNIQUE rather than part of a composite key.
--
-- ⚠️⚠️ `secret_encrypted` PLUS `exec_url` IS A CREDENTIAL FOR THE
--      CUSTOMER'S GOOGLE ACCOUNT.
--
--   An Apps Script web app deployed "execute as me / anyone" runs under
--   the deploying user's authority for whoever holds the URL. The
--   secret is the only thing standing in front of it. So the pair is
--   strictly more dangerous than an API key and is treated like 082's
--   refresh token: AES-256-GCM at rest, decrypted in exactly one
--   service, never in a queue payload, never in a response, never in a
--   log line.
--
-- ⚠️ RLS IS ON WITH ZERO POLICIES AND RIGHTS ARE REVOKED — same
--    reasoning as 082 and admin_audit_log, and for a stronger reason.
--
--   RLS is ROW-level, not column-level. Any policy permitting a browser
--   to read its own workspace's row hands `secret_encrypted` to
--   PostgREST. There is no "everything except that column" policy to
--   write. This table is API-only and the API returns a redacted
--   projection. Add an endpoint, never a policy.
--
--   Note the deliberate contrast with `media_assets` (087), which IS
--   browser-written under RLS: that table holds a filename and a URL
--   that is already public. This one holds a live credential.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.google_script_connections (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- One bridge per workspace. UNIQUE, not just indexed: two rows would
  -- make "which script does this automation call?" ambiguous, and the
  -- executor resolves by account_id alone.
  account_id   uuid NOT NULL UNIQUE
                 REFERENCES public.accounts(id) ON DELETE CASCADE,

  -- The /exec deployment URL. Validated in the API against
  -- script.google.com so a pasted value cannot point the executor at an
  -- arbitrary host — the step config carries no URL of its own, which is
  -- the same "author-supplied data is not authority" rule that
  -- app_connections' connection_id needed.
  exec_url     text NOT NULL,

  -- AES-256-GCM, via common/security/encryption.util. Generated BY US
  -- and shown to the customer exactly once, pre-filled into the script
  -- we hand them — they never invent it, and we never need it back.
  secret_encrypted text NOT NULL,

  -- Result of the last real call, so the Integrations page can say
  -- "working" rather than "configured". NULL = never exercised.
  last_ok_at   timestamptz,
  last_error   text,
  last_error_at timestamptz,

  -- Who pasted it in. NULL if the row outlives the profile.
  created_by   uuid REFERENCES public.profiles(id) ON DELETE SET NULL,

  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.google_script_connections IS
  'One customer-deployed Apps Script bridge per workspace (Gmail/Calendar/Meet/Sheets). exec_url + secret_encrypted is a credential for their Google account: API-only, RLS on with no policies. See docs/google-apps-script.md.';

COMMENT ON COLUMN public.google_script_connections.exec_url IS
  'Apps Script /exec deployment URL. Host-validated in the API; never taken from step config.';

COMMENT ON COLUMN public.google_script_connections.secret_encrypted IS
  'AES-256-GCM. Generated server-side, shown to the customer once, pre-filled into their script. Never returned by any endpoint.';

ALTER TABLE public.google_script_connections ENABLE ROW LEVEL SECURITY;

-- No policies, by design. With RLS enabled and none defined, every
-- PostgREST read and write is refused; only an owner connection
-- (apps/api) reaches the table.
REVOKE ALL ON public.google_script_connections FROM anon, authenticated;

-- ------------------------------------------------------------
-- Remove the OAuth connector (082).
--
-- Verified before writing this migration: zero automation_steps rows of
-- type 'app_action', zero forms with a calendar availability block, and
-- one app_connections row (a developer's own test). Nothing customer-
-- facing is lost.
--
-- ⚠️ IRREVERSIBLE. Dropping this table destroys the encrypted refresh
--    tokens in it. A workspace that had connected Google must set up a
--    script bridge instead; there is no migration path between the two
--    because they are different mechanisms with different credentials.
--
-- `automation_steps.step_type` has no CHECK constraint (only `branch`
-- does), so retiring the 'app_action' type needs no DDL — it is enforced
-- in application code alone.
-- ------------------------------------------------------------

DROP TABLE IF EXISTS public.app_connections CASCADE;
